# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'samainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SAMainWindow(object):
    def setupUi(self, SAMainWindow):
        SAMainWindow.setObjectName("SAMainWindow")
        SAMainWindow.resize(1427, 724)
        self.centralWidget = QtWidgets.QWidget(SAMainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(50, 60, 1351, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(100, 20, 741, 341))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(11, 11, 20, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.NameInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.NameInput.setObjectName("NameInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.NameInput)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.DateInput = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.DateInput.setObjectName("DateInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.DateInput)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.TimeInput = QtWidgets.QTimeEdit(self.formLayoutWidget)
        self.TimeInput.setObjectName("TimeInput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.TimeInput)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.locstring = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.locstring.setObjectName("locstring")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.locstring)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_9)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.Timezone = QtWidgets.QComboBox(self.formLayoutWidget)
        self.Timezone.setObjectName("Timezone")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.Timezone)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.latDisplay = QtWidgets.QLabel(self.formLayoutWidget)
        self.latDisplay.setText("")
        self.latDisplay.setObjectName("latDisplay")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.latDisplay)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.longDisplay = QtWidgets.QLabel(self.formLayoutWidget)
        self.longDisplay.setText("")
        self.longDisplay.setObjectName("longDisplay")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.longDisplay)
        self.savebirth = QtWidgets.QPushButton(self.tab)
        self.savebirth.setGeometry(QtCore.QRect(410, 370, 151, 32))
        self.savebirth.setObjectName("savebirth")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Planet_Dignity = QtWidgets.QTableWidget(self.tab_2)
        self.Planet_Dignity.setGeometry(QtCore.QRect(0, 0, 1341, 261))
        self.Planet_Dignity.setObjectName("Planet_Dignity")
        self.Planet_Dignity.setColumnCount(12)
        self.Planet_Dignity.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.Planet_Dignity.setHorizontalHeaderItem(11, item)
        self.Sign_table = QtWidgets.QTableWidget(self.tab_2)
        self.Sign_table.setGeometry(QtCore.QRect(0, 300, 1351, 121))
        self.Sign_table.setObjectName("Sign_table")
        self.Sign_table.setColumnCount(12)
        self.Sign_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.Sign_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sign_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sign_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sign_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sign_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sign_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sign_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sign_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sign_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sign_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sign_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sign_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sign_table.setHorizontalHeaderItem(11, item)
        self.HouseTable = QtWidgets.QTableWidget(self.tab_2)
        self.HouseTable.setGeometry(QtCore.QRect(0, 430, 1341, 121))
        self.HouseTable.setObjectName("HouseTable")
        self.HouseTable.setColumnCount(12)
        self.HouseTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.HouseTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.HouseTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.HouseTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.HouseTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.HouseTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.HouseTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.HouseTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.HouseTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.HouseTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.HouseTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.HouseTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.HouseTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.HouseTable.setHorizontalHeaderItem(11, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 10, 1241, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Chartname = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.Chartname.setObjectName("Chartname")
        self.horizontalLayout.addWidget(self.Chartname)
        self.LoadChart = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.LoadChart.setObjectName("LoadChart")
        self.horizontalLayout.addWidget(self.LoadChart)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.title = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.title.setText("")
        self.title.setObjectName("title")
        self.horizontalLayout.addWidget(self.title)
        SAMainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(SAMainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1427, 22))
        self.menuBar.setObjectName("menuBar")
        SAMainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(SAMainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        SAMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(SAMainWindow)
        self.statusBar.setObjectName("statusBar")
        SAMainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(SAMainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SAMainWindow)

    def retranslateUi(self, SAMainWindow):
        _translate = QtCore.QCoreApplication.translate
        SAMainWindow.setWindowTitle(_translate("SAMainWindow", "MainWindow"))
        self.label.setText(_translate("SAMainWindow", "Name"))
        self.label_2.setText(_translate("SAMainWindow", "Date"))
        self.DateInput.setDisplayFormat(_translate("SAMainWindow", "M/d/yyyy"))
        self.label_4.setText(_translate("SAMainWindow", "Time"))
        self.TimeInput.setDisplayFormat(_translate("SAMainWindow", "hh:mm"))
        self.label_3.setText(_translate("SAMainWindow", "Location"))
        self.label_9.setText(_translate("SAMainWindow", "Location format: City, State, Country"))
        self.label_5.setText(_translate("SAMainWindow", "TimeZone"))
        self.label_7.setText(_translate("SAMainWindow", "Long"))
        self.label_10.setText(_translate("SAMainWindow", "Lat"))
        self.savebirth.setText(_translate("SAMainWindow", "Save Birth Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SAMainWindow", "Birth data"))
        item = self.Planet_Dignity.verticalHeaderItem(0)
        item.setText(_translate("SAMainWindow", "SUN"))
        item = self.Planet_Dignity.verticalHeaderItem(1)
        item.setText(_translate("SAMainWindow", "MOON"))
        item = self.Planet_Dignity.verticalHeaderItem(2)
        item.setText(_translate("SAMainWindow", "MERC"))
        item = self.Planet_Dignity.verticalHeaderItem(3)
        item.setText(_translate("SAMainWindow", "VENUS"))
        item = self.Planet_Dignity.verticalHeaderItem(4)
        item.setText(_translate("SAMainWindow", "MARS"))
        item = self.Planet_Dignity.verticalHeaderItem(5)
        item.setText(_translate("SAMainWindow", "JUPITER"))
        item = self.Planet_Dignity.verticalHeaderItem(6)
        item.setText(_translate("SAMainWindow", "SATURN"))
        item = self.Planet_Dignity.verticalHeaderItem(7)
        item.setText(_translate("SAMainWindow", "RAHU"))
        item = self.Planet_Dignity.verticalHeaderItem(8)
        item.setText(_translate("SAMainWindow", "KETU"))
        item = self.Planet_Dignity.horizontalHeaderItem(0)
        item.setText(_translate("SAMainWindow", "Planet Name"))
        item = self.Planet_Dignity.horizontalHeaderItem(1)
        item.setText(_translate("SAMainWindow", "Lagna"))
        item = self.Planet_Dignity.horizontalHeaderItem(2)
        item.setText(_translate("SAMainWindow", "Lagna Lord"))
        item = self.Planet_Dignity.horizontalHeaderItem(3)
        item.setText(_translate("SAMainWindow", "Exalt"))
        item = self.Planet_Dignity.horizontalHeaderItem(4)
        item.setText(_translate("SAMainWindow", "Fallen"))
        item = self.Planet_Dignity.horizontalHeaderItem(5)
        item.setText(_translate("SAMainWindow", "Trik"))
        item = self.Planet_Dignity.horizontalHeaderItem(6)
        item.setText(_translate("SAMainWindow", "P.Friend"))
        item = self.Planet_Dignity.horizontalHeaderItem(7)
        item.setText(_translate("SAMainWindow", "P.Enemy"))
        item = self.Planet_Dignity.horizontalHeaderItem(8)
        item.setText(_translate("SAMainWindow", "P.Neutral"))
        item = self.Planet_Dignity.horizontalHeaderItem(9)
        item.setText(_translate("SAMainWindow", "T.Friend"))
        item = self.Planet_Dignity.horizontalHeaderItem(10)
        item.setText(_translate("SAMainWindow", "T.Enemy"))
        item = self.Planet_Dignity.horizontalHeaderItem(11)
        item.setText(_translate("SAMainWindow", "Dignity"))
        item = self.Sign_table.verticalHeaderItem(0)
        item.setText(_translate("SAMainWindow", "Planets"))
        item = self.Sign_table.horizontalHeaderItem(0)
        item.setText(_translate("SAMainWindow", "Aries"))
        item = self.Sign_table.horizontalHeaderItem(1)
        item.setText(_translate("SAMainWindow", "Taurus"))
        item = self.Sign_table.horizontalHeaderItem(2)
        item.setText(_translate("SAMainWindow", "Gemini"))
        item = self.Sign_table.horizontalHeaderItem(3)
        item.setText(_translate("SAMainWindow", "Cancer"))
        item = self.Sign_table.horizontalHeaderItem(4)
        item.setText(_translate("SAMainWindow", "Leo"))
        item = self.Sign_table.horizontalHeaderItem(5)
        item.setText(_translate("SAMainWindow", "Virgo"))
        item = self.Sign_table.horizontalHeaderItem(6)
        item.setText(_translate("SAMainWindow", "Libra"))
        item = self.Sign_table.horizontalHeaderItem(7)
        item.setText(_translate("SAMainWindow", "Scorpio"))
        item = self.Sign_table.horizontalHeaderItem(8)
        item.setText(_translate("SAMainWindow", "Sagittarius"))
        item = self.Sign_table.horizontalHeaderItem(9)
        item.setText(_translate("SAMainWindow", "Capricorn"))
        item = self.Sign_table.horizontalHeaderItem(10)
        item.setText(_translate("SAMainWindow", "Aquarius"))
        item = self.Sign_table.horizontalHeaderItem(11)
        item.setText(_translate("SAMainWindow", "Pisces"))
        item = self.HouseTable.verticalHeaderItem(0)
        item.setText(_translate("SAMainWindow", "Planets"))
        item = self.HouseTable.horizontalHeaderItem(0)
        item.setText(_translate("SAMainWindow", "1st House"))
        item = self.HouseTable.horizontalHeaderItem(1)
        item.setText(_translate("SAMainWindow", "2nd House"))
        item = self.HouseTable.horizontalHeaderItem(2)
        item.setText(_translate("SAMainWindow", "3rd House"))
        item = self.HouseTable.horizontalHeaderItem(3)
        item.setText(_translate("SAMainWindow", "4th House"))
        item = self.HouseTable.horizontalHeaderItem(4)
        item.setText(_translate("SAMainWindow", "5th House"))
        item = self.HouseTable.horizontalHeaderItem(5)
        item.setText(_translate("SAMainWindow", "6th House"))
        item = self.HouseTable.horizontalHeaderItem(6)
        item.setText(_translate("SAMainWindow", "7th House"))
        item = self.HouseTable.horizontalHeaderItem(7)
        item.setText(_translate("SAMainWindow", "8th House"))
        item = self.HouseTable.horizontalHeaderItem(8)
        item.setText(_translate("SAMainWindow", "9th House"))
        item = self.HouseTable.horizontalHeaderItem(9)
        item.setText(_translate("SAMainWindow", "10th House"))
        item = self.HouseTable.horizontalHeaderItem(10)
        item.setText(_translate("SAMainWindow", "11th House"))
        item = self.HouseTable.horizontalHeaderItem(11)
        item.setText(_translate("SAMainWindow", "12th House"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SAMainWindow", "Chart"))
        self.LoadChart.setText(_translate("SAMainWindow", "Load"))
        self.label_6.setText(_translate("SAMainWindow", "Horoscope for :"))

